### PR TITLE
Added design resources

### PR DESCRIPTION
**Pull request by tanushree57**
Added design resources

### CODE REVIEW

**Comment by IC1101Virgo** [comment]
Thank you ☕ Merging

**Comment by tanushree57** [comment]
@IC1101Virgo Thanks alot!

**Comment by tanushree57** [comment]
Can I share more?

**Comment by IC1101Virgo** [comment]
@tanushree57 I'm sorry resource adding just one time 😉 I was thinking of enhancing the site so I might add more code-related issues. So stay tuned for them!
Happy coding :)

**Pull request merged**
